### ISSUE TITLE
Error while running main.py => Got unexpected extra argument

### ISSUE THREAD

**Issue by tomarsachin2271** [eli64s/README-AI#18]
I installed python3 and did all the setup. 

When running the command  
`python3 src/main.py --output README_AI.md /Users/sachintomar/github/ethereum_rpc_client `

I'm getting below error

```
Usage: main.py [OPTIONS]
Try 'main.py --help' for help.

Error: Got unexpected extra argument (/Users/sachintomar/github/ethereum_rpc_client)
```

**Comment by eli64s** [comment]
Hi @tomarsachin2271,

Try running the command:

```bash
python3 src/main.py --output README_AI.md --repository /Users/sachintomar/github/ethereum_rpc_client 
```

You must specify the **--repository** argument before typing your repository path or url.

Let me know if that corrects the issue! 

Thank you,
Eli
