### ISSUE TITLE
Authentication failed to github.com

### ISSUE THREAD

**Issue by spongy83** [eli64s/README-AI#2]
Running full command:
`python src/main.py -k KEY -o docs/README_X.md -u GITHUB_URL` and receiving the following error after prompted for username/password:
```
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'GITHUB_URL'
```

KEY and GITHUB_URL were of course fully written out. 
Thanks for what looks like an awesome project!

**Comment by eli64s** [comment]
This should be corrected as many changes have been made to the codebase. 

Please let me know if you're still having issues. Thanks!
