### ISSUE TITLE
Readme for repos with lots of data

### ISSUE THREAD

**Issue by darinkishore** [eli64s/readme-ai#23]
Hi! Before running the script, I want to make sure that it isn't going to send non-code files to GPT. 

In my ./SRC for the intented repo, I have .py, .csv, and .png files. I also have lots of data (17k+) in json files in my ./dat . Will the script send over the json file contents to gpt to process? How do I make sure the jsons are excluded?

**Comment by eli64s** [comment]
Hey. There is a file [conf/ignore_files.toml](https://github.com/eli64s/README-AI/blob/main/conf/ignore_files.toml) where you can add file names, extensions, and directories to exclude.

As always, run some small sample tests to ensure it behaves how you are expecting it too.

**Comment by darinkishore** [comment]
Big respect. Thanks for creating this.
