### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by Alexei7ca** [eli64s/readme-ai#27]
command:

readme-ai % python3 src/main.py --api-key "API_KEY" --output readme-ai.md --repository https://github.com/Alexei7ca/TmsTestProject/readme

Response:

Traceback (most recent call last):
  File "/Users/alexei/readme-ai/src/main.py", line 8, in <module>
    import conf
  File "/Users/alexei/readme-ai/src/conf.py", line 10, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by swamitagupta** [comment]
run 'pip install -r requirements.txt', that would install all the required libraries @Alexei7ca
