### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by johnfelipe** [eli64s/readme-ai#28]
```
(base) root@template:~/readme-ai# conda activate readmeai
(readmeai) root@template:~/readme-ai# export OPENAI_API_KEY="sk-blablablabla"
(readmeai) root@template:~/readme-ai# python src/main.py -o readme-ai.md -r https://github.com/johnfelipe/revisionmanualbasadaensonarconreportingtool
Traceback (most recent call last):
  File "/root/readme-ai/src/main.py", line 8, in <module>
    import conf
  File "/root/readme-ai/src/conf.py", line 10, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
(readmeai) root@template:~/readme-ai# ls
CHANGELOG.md        Dockerfile  poetry.lock       scripts   tests
CODE_OF_CONDUCT.md  examples    pyproject.toml    setup
conf                LICENSE     README.md         setup.py
CONTRIBUTING.md     Makefile    requirements.txt  src
(readmeai) root@template:~/readme-ai# python src/main.py -o readme-ai.md -r https://github.com/eli64s/readme-ai
Traceback (most recent call last):
  File "/root/readme-ai/src/main.py", line 8, in <module>
    import conf
  File "/root/readme-ai/src/conf.py", line 10, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
(readmeai) root@template:~/readme-ai# python src/main.py --api-key "sk-blablablabla" --output readme-ai.md --repository https://github.com/eli64s/readme-ai
Traceback (most recent call last):
  File "/root/readme-ai/src/main.py", line 8, in <module>
    import conf
  File "/root/readme-ai/src/conf.py", line 10, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
```

how fix this?

**Comment by eli64s** [comment]
Did you run the setup script and activate the virtual environment?

```bash
bash setup/setup.sh
```

**Comment by johnfelipe** [comment]
> ```shell
> bash setup/setup.sh
> ```

yes, i do this steps:

bash setup/setup.sh

	Welcome to the README-AI environment setup script!
	Checking for Python 3.7 or higher...
	Python version is compatible.
	Creating a new conda environment named 'readmeai' with Python 3.9...
	Collecting package metadata (current_repodata.json): done
	Solving environment: done

	## Package Plan ##

	  environment location: /root/anaconda3/envs/readmeai

	  added / updated specs:
		- python=3.9


	The following packages will be downloaded:

		package                    |            build
		---------------------------|-----------------
		openssl-3.0.9              |       h7f8727e_0         5.2 MB
		pip-23.1.2                 |   py39h06a4308_0         2.5 MB
		python-3.9.17              |       h955ad1f_0        25.0 MB
		setuptools-67.8.0          |   py39h06a4308_0         1.0 MB
		wheel-0.38.4               |   py39h06a4308_0          64 KB
		------------------------------------------------------------
											   Total:        33.8 MB

	The following NEW packages will be INSTALLED:

	  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
	  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
	  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.05.30-h06a4308_0
	  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
	  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0
	  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
	  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
	  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
	  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
	  openssl            pkgs/main/linux-64::openssl-3.0.9-h7f8727e_0
	  pip                pkgs/main/linux-64::pip-23.1.2-py39h06a4308_0
	  python             pkgs/main/linux-64::python-3.9.17-h955ad1f_0
	  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
	  setuptools         pkgs/main/linux-64::setuptools-67.8.0-py39h06a4308_0
	  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0
	  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
	  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
	  wheel              pkgs/main/linux-64::wheel-0.38.4-py39h06a4308_0
	  xz                 pkgs/main/linux-64::xz-5.4.2-h5eee18b_0
	  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0



	Downloading and Extracting Packages

	Preparing transaction: done
	Verifying transaction: done
	Executing transaction: done
	#
	# To activate this environment, use
	#
	#     $ conda activate readmeai
	#
	# To deactivate an active environment, use
	#
	#     $ conda deactivate

	Activating the 'readmeai' environment...
	Checking if Poetry is installed...
	Poetry is not installed. Installing Poetry...
	Retrieving Poetry metadata

	# Welcome to Poetry!

	This will download and install the latest version of Poetry,
	a dependency and package manager for Python.

	It will add the `poetry` command to Poetry's bin directory, located at:

	/root/.local/bin

	You can uninstall at any time by executing this script with the --uninstall option,
	and these changes will be reverted.

	Installing Poetry (1.5.1): Done

	Poetry (1.5.1) is installed now. Great!

	To get started you need Poetry's bin directory (/root/.local/bin) in your `PATH`
	environment variable.

	Add `export PATH="/root/.local/bin:$PATH"` to your shell configuration file.

	Alternatively, you can call Poetry explicitly with `/root/.local/bin/poetry`.

	You can test that everything is set up by executing:

	`poetry --version`

	setup/setup.sh: line 101: cd: readme-ai: No such file or directory
	Installing project dependencies with Poetry...
	setup/setup.sh: line 105: poetry: command not found
	Setup complete. Use 'conda activate readmeai' to activate the environment.

conda activate readmeai

(readmeai) root@template:~/readme-ai#

**Comment by eli64s** [comment]
After activating the virtual environment, try running:

```sh
pip install -r requirements.txt
```

https://github.com/eli64s/readme-ai/issues/27#issuecomment-1643648187
