### ISSUE TITLE
HTTPStatus Expception: Client error '400 Bad Request'

### ISSUE THREAD

**Issue by JoseAlbDR** [eli64s/readme-ai#35]
Getting that error after Processing all files prompts, here is a snippet:

`INFO     

Processing prompt: src\utils\helpers.js

Response: ...

ERROR    HTTPStatus Exception:
Client error '400 Bad Request' for url 'https://api.openai.com/v1/chat/completions'
For more information check: https://httpstatuses.com/400

ERROR    HTTPStatus Exception:
Client error '400 Bad Request' for url 'https://api.openai.com/v1/chat/completions'
For more information check: https://httpstatuses.com/400`

Im not used to python, so tell me if you need more info about the error, awesome work by the way.

![errorReadmeai](https://github.com/eli64s/readme-ai/assets/128265706/4f52e9d9-1877-4dc5-8f97-77344d85c202)

In the generated README.md

![readmeError](https://github.com/eli64s/readme-ai/assets/128265706/91bcf404-7727-44c1-8241-240d7b03030a)

**Comment by eli64s** [comment]
Hey @JoseAlbDR! I took a look at this error and was able to reproduce it on my machine using your repository.

I think its related to my OpenAI API implementation and the size of your codebase. I'll need to spend more time here debugging, but great catch. 

Thanks for reporting this!

_Eli_

**Comment by JoseAlbDR** [comment]
Thanks to you! I wish I could help but my Python skills are awful

**Comment by eli64s** [comment]
Hey @JoseAlbDR, this should be fixed but let me know if you face anymore issues. Thank you!

_Eli_
