### ISSUE TITLE
Running README-AI locally without GitHub repository URL

### ISSUE THREAD

**Issue by ThomasSanson** [eli64s/README-AI#4]
### Description
I'm trying to run README-AI locally on my machine without a GitHub repository, but I'm facing an issue with the configuration file that requires me to provide a GitHub repository URL. I would like to use a Git repository on my machine instead.

### Steps to reproduce
1. Clone the README-AI repository on your machine
2. Navigate to the cloned repository directory
3. Run the README-AI command with the `--local` flag to specify the local repository path, for example:
```bash
readme-ai --local /path/to/local/repo
```

### Expected behavior
README-AI should generate a README.md file based on the local repository and without requiring a GitHub repository URL.

### Actual behavior
README-AI displays an error message indicating that the GitHub repository URL is missing in the configuration file.

**Comment by swamitagupta** [comment]
@ThomasSanson @eli64s  did you figure out a fix for the same? 
I'm currently running the command 
`python src/main.py --api-key 'mykey' --output readme-ai.md --repository /home/path`

But am facing the error 
ValueError: Error cloning repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --depth=1 -- /home/path /tmp/tmphjpteuyf
  stderr: 'fatal: repository '/home/path' does not exist

**Comment by ThomasSanson** [comment]
Hello @swamitagupta,

Yes, I opted for using Docker because I find it simpler. Here are the steps to set up the environment (please ignore the parts related to proxies if they don't concern you) :

1. Create a Dockerfile anywhere for the Readme-ai project

Dockerfile.readmeai
```Dockerfile
# Build stage
FROM alpine:latest as builder

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG FTP_PROXY
ARG http_proxy
ARG https_proxy
ARG ftp_proxy
ARG no_proxy

ENV http_proxy=$http_proxy \
    https_proxy=$https_proxy \
    ftp_proxy=$ftp_proxy \
    HTTP_PROXY=$HTTP_PROXY \
    HTTPS_PROXY=$HTTPS_PROXY \
    FTP_PROXY=$FTP_PROXY \
    no_proxy=$no_proxy

RUN apk update && apk add git

WORKDIR /app

RUN git clone https://github.com/eli64s/readme-ai.git .

# Final stage
# Use a base image with Python installed
FROM python:3.8-slim-buster

# Set the working directory
WORKDIR /app

# Copy project files into the container
COPY --from=builder /app .

# Install project dependencies
RUN apt update && apt install -y git tree && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Set the command to run your project
CMD ["python", "src/main.py"]
```

2. Next, build the Docker image to get a local image :

```bash
docker build --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTPS_PROXY --build-arg FTP_PROXY=$FTP_PROXY --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg ftp_proxy=$ftp_proxy --build-arg no_proxy=$no_proxy -t my-readme-ai --file Dockerfile.readmeai .
```

This will create a local image named `my-readme-ai`

3. Finally, navigate to your project and run the container with the following command :

Before running this command, you should replace `xxxxxxxxxxxxx` with your own API key

```bash
docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY -e FTP_PROXY=$FTP_PROXY -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e ftp_proxy=$ftp_proxy -e no_proxy=$no_proxy -e OPENAI_API_KEY="xxxxxxxxxxxxx" -v "$(pwd)":/workdir -w /app -it my-readme-ai python src/main.py -o /workdir/readme-ai.md -r /workdir
```

The command utilizes the `-v` flag to mount the current working directory (`pwd`) to the container's `/workdir`. It means that the files and directories in the current directory on the host machine are made accessible to the container within the `/workdir` directory. Additionally, the `-w` flag sets the working directory inside the container to `/app`

We have the actual command to be executed within the container :

```bash
python src/main.py -o /workdir/readme-ai.md -r /workdir
```

Here's what this command does :

- `python src/main.py`: This executes the `main.py` Python script located in the `/app/src` directory within the container. It is the main script of the "Readme-ai" project

- `-o /workdir/readme-ai.md`: This specifies the output file path (`/workdir/readme-ai.md`) where the generated result will be stored. The generated content might be a Markdown file related to the "Readme-ai" project

- `-r /workdir`: This option is used to indicate a specific directory (`/workdir`) where your project code resides inside the container
